### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by andychase** [USEPA/-CompTox-ToxCast-invitrodb#1]
@brown-jason Do you mind if I change the name to "comptox-toxcast-invitrodb". Any existing links to this page will automatically redirect

**Comment by brown-jason** [comment]
That's fine with me

From: Andy Chase ***@***.***>
Sent: Friday, January 14, 2022 4:14 PM
To: USEPA/-CompTox-ToxCast-invitrodb ***@***.***>
Cc: Brown, Jason ***@***.***>; Mention ***@***.***>
Subject: [USEPA/-CompTox-ToxCast-invitrodb] Name change (Issue #1)


@brown-jason<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrown-jason&data=04%7C01%7Cbrown.jason%40epa.gov%7C145f33634213494883bd08d9d7a2d805%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637777917155612114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FhHMMILgE9iHKAnW8ut25xVG4%2B1xxxRrwPTvMPZpEcw%3D&reserved=0> Do you mind if I change the name to "comptox-toxcast-invitrodb". Any existing links to this page will automatically redirect

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSEPA%2F-CompTox-ToxCast-invitrodb%2Fissues%2F1&data=04%7C01%7Cbrown.jason%40epa.gov%7C145f33634213494883bd08d9d7a2d805%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637777917155612114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0lAJtlXFRb9JmBTkAuU%2BfMuUQvvSgdHCl6QO38yjSt8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKGKM75G4DLT4W5JOARGSMTUWCG3BANCNFSM5L7YXJLQ&data=04%7C01%7Cbrown.jason%40epa.gov%7C145f33634213494883bd08d9d7a2d805%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637777917155768777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZF1PHOT9xxFU6kVjBQqgbuzBqT%2B2HeQtbkgmp%2F9a8hc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbrown.jason%40epa.gov%7C145f33634213494883bd08d9d7a2d805%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637777917155768777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XdXDiRZwHpSTop8cQbVMmqu9VMIMAyp3bQhYaAQ%2BwPI%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbrown.jason%40epa.gov%7C145f33634213494883bd08d9d7a2d805%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C637777917155768777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sOqT6ynG%2F9QXQKoMSLMJlWHypRnmq9SqjDKzq9olo5Y%3D&reserved=0>.
